version: '3.8'

services:
  php:
    build: ./docker/php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
      - ./log:/var/log/apache2
      - ./apache2:/etc/apache2/
      - ./ssl:/etc/letsencrypt/
      #- ./phpini:/usr/local/etc/php
      #- ./apache_conf/apache2/:/etc/apache2/
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      # - mysql-data:/var/lib/mysql
      - mysql-data-1:/var/lib/mysql
      - ./dumpbd:/dumpbd
    environment:
      MYSQL_ROOT_PASSWORD: 6b_ecXVu3Z
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
  phpmyadmin:
    image: phpmyadmin:apache
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    #  PMA_USER: root
    #  PMA_PASSWORD: 123
    depends_on:
      - mysql
volumes:
  # mysql-data:
  mysql-data-1: